### ISSUE TITLE
Mention of the application

### ISSUE THREAD

**Issue by izyumkin** [unorderly/Klang#1]
Hi! This is an awesome app. Glad to see my emoji picker library involved in this project!

I'd like to add your app to the [Apps Using](https://github.com/izyumkin/MCEmojiPicker#apps-using) section in the README of the repository, do you mind?

**Comment by leoMehlig** [comment]
@izyumkin Sure thing! Thanks so much for building this library. It's an awesome project and I hope I can contribute soon!
