### ISSUE TITLE
Hi Leo, I have a question about AudioPlayer

### ISSUE THREAD

**Issue by rijieli** [unorderly/Klang#6]
Why does this class add an `@Observable` in `App/Audio/AudioPlayer.swift`? It seems there are no variables related to view updates.

```
@Observable
public final class AudioPlayer: NSObject, AVAudioPlayerDelegate {
    ...
}
```

**Comment by leoMehlig** [comment]
@rijieli `isPlaying` and `progress` are both related to view updates.
